# Generated by Django 6.0.7 on 2026-07-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userprofile_country_remove_userprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_delivery_person',
            field=models.BooleanField(default=False),
        ),
    ]
